### ISSUE TITLE
`FlattenRelabelRegistersPass` removes blank classical wires

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/tket#1434]
This is inconvenient because it leaves incomplete classical registers. It should only remove blank quantum wires. (We could either give `Circuit::remove_blank_wires()` an optional argument to specify this or add a new method.

**Comment by CalMacCQ** [comment]
is this now fixed by #1435 ?

**Comment by cqc-alec** [comment]
> is this now fixed by #1435 ?

Yes.

**Comment by cqc-alec** [comment]
This is not fixed: #1435 didn't change the behaviour of the pass.
